// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class ConsentForm : IEntityBase
{
    public int ConsentFormId { get; set; }

    public int? FormId { get; set; }

    public int? ParentId { get; set; }

    public int? Status { get; set; }

    public virtual Form Form { get; set; }

    public virtual Parent Parent { get; set; }
}