// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class Form : IEntityBase
{
    public int FormId { get; set; }

    public int? ManagerId { get; set; }

    public DateTime? SentDate { get; set; }

    public string ClassName { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int Type { get; set; }

    public virtual ICollection<ConsentForm> ConsentForms { get; set; } = new List<ConsentForm>();

    public virtual ICollection<HealthCheckSchedule> HealthCheckSchedules { get; set; } = new List<HealthCheckSchedule>();

    public virtual Manager Manager { get; set; }

    public virtual ICollection<VaccinationSchedule> VaccinationSchedules { get; set; } = new List<VaccinationSchedule>();
}