// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class HealthCheckSchedule : IEntityBase
{
    public int HealthCheckScheduleId { get; set; }

    public int? FormId { get; set; }

    public int? ManagerId { get; set; }

    public string Name { get; set; }

    public DateTime? CheckDate { get; set; }

    public string Location { get; set; }

    public string Note { get; set; }

    public virtual Form Form { get; set; }

    public virtual ICollection<HealthCheckResult> HealthCheckResults { get; set; } = new List<HealthCheckResult>();

    public virtual Manager Manager { get; set; }
}