// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class MedicalEvent : IEntityBase
{
    public int EventId { get; set; }

    public int? StudentId { get; set; }

    public int? NurseId { get; set; }

    public string EventName { get; set; }

    public DateTime? EventDate { get; set; }

    public string Symptoms { get; set; }

    public string ActionTaken { get; set; }

    public string Note { get; set; }

    public virtual Nurse Nurse { get; set; }

    public virtual Student Student { get; set; }
}