// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class MedicalInventory : IEntityBase
{
    public int MedicalInventoryId { get; set; }

    public int? ManagerId { get; set; }

    public int? Quantity { get; set; }

    public string MedicalName { get; set; }

    public string Unit { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public DateOnly? DateAdded { get; set; }

    public virtual Manager Manager { get; set; }
}