// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class Parent : IEntityBase
{
    public int ParentId { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string PasswordHash { get; set; }

    public string ActivationCode { get; set; }  

    public bool IsActive { get; set; }       

    public string Note { get; set; }       

    public virtual ICollection<ConsentForm> ConsentForms { get; set; } = new List<ConsentForm>();

    public virtual ICollection<ConsultationForm> ConsultationForms { get; set; } = new List<ConsultationForm>();

    public virtual ICollection<ParentPrescription> ParentPrescriptions { get; set; } = new List<ParentPrescription>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}