// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class ParentPrescription : IEntityBase
{
    public int PrescriptionId { get; set; }

    public int? NurseId { get; set; }

    public DateOnly? SubmittedDate { get; set; }

    public string Schedule { get; set; }

    public string ParentNote { get; set; }

    public int? ParentId { get; set; }

    public string PrescriptionFile { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Medication> Medications { get; set; } = new List<Medication>();

    public virtual Nurse Nurse { get; set; }

    public virtual Parent Parent { get; set; }
}