// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Smmsbe.Repositories.Entities;

public partial class SMMSContext : DbContext
{
    public SMMSContext(DbContextOptions<SMMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Blog> Blogs { get; set; }

    public virtual DbSet<ConsentForm> ConsentForms { get; set; }

    public virtual DbSet<ConsultationForm> ConsultationForms { get; set; }

    public virtual DbSet<ConsultationSchedule> ConsultationSchedules { get; set; }

    public virtual DbSet<Form> Forms { get; set; }

    public virtual DbSet<HealthCheckResult> HealthCheckResults { get; set; }

    public virtual DbSet<HealthCheckSchedule> HealthCheckSchedules { get; set; }

    public virtual DbSet<HealthProfile> HealthProfiles { get; set; }

    public virtual DbSet<Manager> Managers { get; set; }

    public virtual DbSet<MedicalEvent> MedicalEvents { get; set; }

    public virtual DbSet<MedicalInventory> MedicalInventories { get; set; }

    public virtual DbSet<Medication> Medications { get; set; }

    public virtual DbSet<Nurse> Nurses { get; set; }

    public virtual DbSet<Parent> Parents { get; set; }

    public virtual DbSet<ParentPrescription> ParentPrescriptions { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<VaccinationResult> VaccinationResults { get; set; }

    public virtual DbSet<VaccinationSchedule> VaccinationSchedules { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(entity =>
        {
            entity.HasKey(e => e.BlogId).HasName("PK__Blog__54379E30CB7A40D6");

            entity.ToTable("Blog");

            entity.Property(e => e.Thumbnail).HasMaxLength(200);
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Manager).WithMany(p => p.Blogs)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK__Blog__ManagerId__6C190EBB");
        });

        modelBuilder.Entity<ConsentForm>(entity =>
        {
            entity.HasKey(e => e.ConsentFormId).HasName("PK__ConsentF__D6F184C05D279FB1");

            entity.ToTable("ConsentForm");

            entity.HasOne(d => d.Form).WithMany(p => p.ConsentForms)
                .HasForeignKey(d => d.FormId)
                .HasConstraintName("FK_ConsentForm_Form");

            entity.HasOne(d => d.Parent).WithMany(p => p.ConsentForms)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK__ConsentFo__Paren__6D0D32F4");
        });

        modelBuilder.Entity<ConsultationForm>(entity =>
        {
            entity.HasKey(e => e.ConsultationFormId).HasName("PK__Consulta__1F12164408C9A26A");

            entity.ToTable("ConsultationForm");

            entity.Property(e => e.Content).HasMaxLength(250);
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.ConsultationSchedule).WithMany(p => p.ConsultationForms)
                .HasForeignKey(d => d.ConsultationScheduleId)
                .HasConstraintName("FK_ConsultationForm_ConsultationSchedule");

            entity.HasOne(d => d.Parent).WithMany(p => p.ConsultationForms)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK__Consultat__Paren__6EF57B66");
        });

        modelBuilder.Entity<ConsultationSchedule>(entity =>
        {
            entity.HasKey(e => e.ConsultationScheduleId).HasName("PK__Consulta__E128EB77987609A5");

            entity.ToTable("ConsultationSchedule");

            entity.Property(e => e.ConsultDate).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(250);

            entity.HasOne(d => d.Nurse).WithMany(p => p.ConsultationSchedules)
                .HasForeignKey(d => d.NurseId)
                .HasConstraintName("FK__Consultat__Nurse__70DDC3D8");

            entity.HasOne(d => d.Student).WithMany(p => p.ConsultationSchedules)
                .HasForeignKey(d => d.StudentId)
                .HasConstraintName("FK_ConsultationSchedule_Student");
        });

        modelBuilder.Entity<Form>(entity =>
        {
            entity.HasKey(e => e.FormId).HasName("PK__Form__FB05B7DDF1589932");

            entity.ToTable("Form");

            entity.Property(e => e.ClassName).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.SentDate).HasColumnType("datetime");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Manager).WithMany(p => p.Forms)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK__Form__ManagerId__66603565");
        });

        modelBuilder.Entity<HealthCheckResult>(entity =>
        {
            entity.HasKey(e => e.HealthCheckupRecordId).HasName("PK__HealthCh__96C627663748BE55");

            entity.ToTable("HealthCheckResult");

            entity.Property(e => e.LeftVision).HasMaxLength(10);
            entity.Property(e => e.Note).HasMaxLength(250);
            entity.Property(e => e.Result).HasMaxLength(150);
            entity.Property(e => e.RightVision).HasMaxLength(10);

            entity.HasOne(d => d.HealthCheckSchedule).WithMany(p => p.HealthCheckResults)
                .HasForeignKey(d => d.HealthCheckScheduleId)
                .HasConstraintName("FK__HealthChe__Healt__72C60C4A");

            entity.HasOne(d => d.HealthProfile).WithMany(p => p.HealthCheckResults)
                .HasForeignKey(d => d.HealthProfileId)
                .HasConstraintName("FK__HealthChe__Healt__73BA3083");

            entity.HasOne(d => d.Nurse).WithMany(p => p.HealthCheckResults)
                .HasForeignKey(d => d.NurseId)
                .HasConstraintName("FK__HealthChe__Nurse__74AE54BC");
        });

        modelBuilder.Entity<HealthCheckSchedule>(entity =>
        {
            entity.HasKey(e => e.HealthCheckScheduleId).HasName("PK__HealthCh__C109A821C626BCBB");

            entity.ToTable("HealthCheckSchedule");

            entity.Property(e => e.CheckDate).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Note).HasMaxLength(250);

            entity.HasOne(d => d.Form).WithMany(p => p.HealthCheckSchedules)
                .HasForeignKey(d => d.FormId)
                .HasConstraintName("FK__HealthChe__FormI__74AE54BC");

            entity.HasOne(d => d.Manager).WithMany(p => p.HealthCheckSchedules)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK__HealthChe__Manag__76969D2E");
        });

        modelBuilder.Entity<HealthProfile>(entity =>
        {
            entity.HasKey(e => e.HealthProfileId).HasName("PK__HealthPr__73C2C2D53475FB4E");

            entity.ToTable("HealthProfile");

            entity.Property(e => e.Allergies).HasMaxLength(200);
            entity.Property(e => e.BloodType).HasMaxLength(5);

            entity.HasOne(d => d.Student).WithMany(p => p.HealthProfiles)
                .HasForeignKey(d => d.StudentId)
                .HasConstraintName("FK__HealthPro__Stude__6383C8BA");
        });

        modelBuilder.Entity<Manager>(entity =>
        {
            entity.HasKey(e => e.ManagerId).HasName("PK__Manager__3BA2AAE12FE82E96");

            entity.ToTable("Manager");

            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.PasswordHash).HasMaxLength(256);
            entity.Property(e => e.PhoneNumber).HasMaxLength(15);
        });

        modelBuilder.Entity<MedicalEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__MedicalE__7944C810172200E4");

            entity.ToTable("MedicalEvent");

            entity.Property(e => e.ActionTaken).HasMaxLength(100);
            entity.Property(e => e.EventDate).HasColumnType("datetime");
            entity.Property(e => e.EventName).HasMaxLength(100);
            entity.Property(e => e.Note).HasMaxLength(250);
            entity.Property(e => e.Symptoms).HasMaxLength(100);

            entity.HasOne(d => d.Nurse).WithMany(p => p.MedicalEvents)
                .HasForeignKey(d => d.NurseId)
                .HasConstraintName("FK__MedicalEv__Nurse__787EE5A0");

            entity.HasOne(d => d.Student).WithMany(p => p.MedicalEvents)
                .HasForeignKey(d => d.StudentId)
                .HasConstraintName("FK__MedicalEv__Stude__59FA5E80");
        });

        modelBuilder.Entity<MedicalInventory>(entity =>
        {
            entity.HasKey(e => e.MedicalInventoryId).HasName("PK__MedicalI__63F72239EA6D20CD");

            entity.ToTable("MedicalInventory");

            entity.Property(e => e.MedicalName).HasMaxLength(50);
            entity.Property(e => e.Unit).HasMaxLength(20);

            entity.HasOne(d => d.Manager).WithMany(p => p.MedicalInventories)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK__MedicalIn__Manag__7A672E12");
        });

        modelBuilder.Entity<Medication>(entity =>
        {
            entity.HasKey(e => e.MedicationId).HasName("PK__Medicati__62EC1AFAA0D7BF21");

            entity.Property(e => e.Dosage).HasMaxLength(50);
            entity.Property(e => e.MedicationName).HasMaxLength(100);

            entity.HasOne(d => d.Prescription).WithMany(p => p.Medications)
                .HasForeignKey(d => d.PrescriptionId)
                .HasConstraintName("FK_Medications_Prescription");

            entity.HasOne(d => d.Student).WithMany(p => p.Medications)
                .HasForeignKey(d => d.StudentId)
                .HasConstraintName("FK__Medicatio__Stude__52593CB8");
        });

        modelBuilder.Entity<Nurse>(entity =>
        {
            entity.HasKey(e => e.NurseId).HasName("PK__Nurse__43847849446E63B3");

            entity.ToTable("Nurse");

            entity.Property(e => e.ActivationCode).HasMaxLength(32);  
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);     
            entity.Property(e => e.Note).HasMaxLength(256);   
            entity.Property(e => e.PasswordHash).HasMaxLength(256);
            entity.Property(e => e.Username).HasMaxLength(100);
        });

        modelBuilder.Entity<Parent>(entity =>
        {
            entity.HasKey(e => e.ParentId).HasName("PK__Parent__D339516F4CE31658");

            entity.ToTable("Parent");

            entity.Property(e => e.ActivationCode).HasMaxLength(32);   
            entity.Property(e => e.Address).HasMaxLength(250);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.Note).HasMaxLength(256);      
            entity.Property(e => e.PasswordHash).HasMaxLength(256);
            entity.Property(e => e.PhoneNumber).HasMaxLength(15);
        });

        modelBuilder.Entity<ParentPrescription>(entity =>
        {
            entity.HasKey(e => e.PrescriptionId).HasName("PK__ParentPr__4013083278A7E324");

            entity.ToTable("ParentPrescription");

            entity.Property(e => e.ParentNote).HasMaxLength(100);
            entity.Property(e => e.PrescriptionFile)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Schedule).HasMaxLength(100);

            entity.HasOne(d => d.Nurse).WithMany(p => p.ParentPrescriptions)
                .HasForeignKey(d => d.NurseId)
                .HasConstraintName("FK__ParentPre__Nurse__7C4F7684");

            entity.HasOne(d => d.Parent).WithMany(p => p.ParentPrescriptions)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK__ParentPre__Paren__7D439ABD");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK__Student__32C52B99EC604026");

            entity.ToTable("Student");

            entity.Property(e => e.ClassName).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.Gender).HasMaxLength(10);
            entity.Property(e => e.PasswordHash).HasMaxLength(256);
            entity.Property(e => e.StudentNumber).HasMaxLength(100);

            entity.HasOne(d => d.Parent).WithMany(p => p.Students)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK__Student__ParentI__4D94879B");
        });

        modelBuilder.Entity<VaccinationResult>(entity =>
        {
            entity.HasKey(e => e.VaccinationResultId).HasName("PK__Vaccinat__12DE8FF986ABA0AD");

            entity.ToTable("VaccinationResult");

            entity.Property(e => e.Note).HasMaxLength(150);

            entity.HasOne(d => d.HealthProfile).WithMany(p => p.VaccinationResults)
                .HasForeignKey(d => d.HealthProfileId)
                .HasConstraintName("FK__Vaccinati__Healt__7F2BE32F");

            entity.HasOne(d => d.Nurse).WithMany(p => p.VaccinationResults)
                .HasForeignKey(d => d.NurseId)
                .HasConstraintName("FK__Vaccinati__Nurse__00200768");

            entity.HasOne(d => d.VaccinationSchedule).WithMany(p => p.VaccinationResults)
                .HasForeignKey(d => d.VaccinationScheduleId)
                .HasConstraintName("FK__Vaccinati__Vacci__01142BA1");
        });

        modelBuilder.Entity<VaccinationSchedule>(entity =>
        {
            entity.HasKey(e => e.VaccinationScheduleId).HasName("PK__Vaccinat__DC54EC50B02F1D52");

            entity.ToTable("VaccinationSchedule");

            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Note).HasMaxLength(250);
            entity.Property(e => e.ScheduleDate).HasColumnType("datetime");

            entity.HasOne(d => d.Form).WithMany(p => p.VaccinationSchedules)
                .HasForeignKey(d => d.FormId)
                .HasConstraintName("FK__Vaccinati__FormI__7D439ABD");

            entity.HasOne(d => d.Manager).WithMany(p => p.VaccinationSchedules)
                .HasForeignKey(d => d.ManagerId)
                .HasConstraintName("FK__Vaccinati__Manag__02FC7413");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}