// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class Student : IEntityBase
{
    public int StudentId { get; set; }

    public int? ParentId { get; set; }

    public string FullName { get; set; }

    public string StudentNumber { get; set; }

    public string ClassName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string PasswordHash { get; set; }

    public virtual ICollection<ConsultationSchedule> ConsultationSchedules { get; set; } = new List<ConsultationSchedule>();

    public virtual ICollection<HealthProfile> HealthProfiles { get; set; } = new List<HealthProfile>();

    public virtual ICollection<MedicalEvent> MedicalEvents { get; set; } = new List<MedicalEvent>();

    public virtual ICollection<Medication> Medications { get; set; } = new List<Medication>();

    public virtual Parent Parent { get; set; }
}