// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class VaccinationSchedule : IEntityBase
{
    public int VaccinationScheduleId { get; set; }

    public int? FormId { get; set; }

    public int? ManagerId { get; set; }

    public string Name { get; set; }

    public DateTime? ScheduleDate { get; set; }

    public string Location { get; set; }

    public string Note { get; set; }

    public virtual Form Form { get; set; }

    public virtual Manager Manager { get; set; }

    public virtual ICollection<VaccinationResult> VaccinationResults { get; set; } = new List<VaccinationResult>();
}