// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Smmsbe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace Smmsbe.Repositories.Entities;

public partial class VaccinationResult : IEntityBase
{
    public int VaccinationResultId { get; set; }

    public int? VaccinationScheduleId { get; set; }

    public int? HealthProfileId { get; set; }

    public int? NurseId { get; set; }

    public int? Status { get; set; }

    public int? DoseNumber { get; set; }

    public string Note { get; set; }

    public virtual HealthProfile HealthProfile { get; set; }

    public virtual Nurse Nurse { get; set; }

    public virtual VaccinationSchedule VaccinationSchedule { get; set; }
}